import json
from datetime import datetime, timedelta

# Base date: August 6, 2026
base_date = datetime(2026, 8, 6)

images = [
    "/static/images/camp_stem_robotics_1786053005743.png",
    "/static/images/camp_art_clay_1786053028373.png",
    "/static/images/camp_nature_explore_1786053051553.png",
    "/static/images/camp_sports_play_1786053075124.png"
]

# Grounded Real San Francisco Programs (94103 / SF Region)
sf_programs = [
    {
        "city": "San Francisco",
        "region": "SF",
        "zip_codes": ["94103", "94102", "94110", "94107", "94118", "94115"],
        "name": "Steve & Kate's Camp (SF Mission Site)",
        "organizer": "Steve & Kate's Camp",
        "category": "STEM",
        "short_description": "Choice-based day camp where kids choose coding, sewing, sports, baking, and filmmaking.",
        "description": "At Steve & Kate's Camp, kids step into a world of choice! Campers choose from a variety of creative and tech studios including stop-motion animation, coding, sewing, bakeries, and sports. Operating on a flexible day-pass system with full lunch included.",
        "cost": "$125 / day",
        "cost_value": 375,
        "age_range": "4 - 12 yrs",
        "pills": ["Choice-Based", "Flexible Passes", "Top Rated"],
        "img_idx": 0,
        "address": "Children's Day School, 333 Valencia St, Mission, SF (1.2 mi away)",
        "dist": 1.2,
        "website": "https://steveandkatescamp.com/san-francisco"
    },
    {
        "city": "San Francisco",
        "region": "SF",
        "zip_codes": ["94103", "94107", "94102"],
        "name": "Children's Creativity Museum Claymation & Media Lab",
        "organizer": "Children's Creativity Museum",
        "category": "Arts",
        "short_description": "Hands-on claymation stop-motion, music recording, and digital art in Yerba Buena.",
        "description": "Located in SoMa right next to Yerba Buena Gardens! Children learn script writing, clay character sculpting, stop-motion camera capture, and digital audio recording to produce their own short claymation film.",
        "cost": "$310 / week",
        "cost_value": 310,
        "age_range": "5 - 12 yrs",
        "pills": ["Claymation", "SoMa Local", "Media Arts"],
        "img_idx": 1,
        "address": "221 4th St, Yerba Buena / SoMa, SF 94103 (0.3 mi away)",
        "dist": 0.3,
        "website": "https://creativity.org"
    },
    {
        "city": "San Francisco",
        "region": "SF",
        "zip_codes": ["94103", "94110", "94114"],
        "name": "Tree Frog Treks Wild Science & Animal Camp",
        "organizer": "Tree Frog Treks",
        "category": "Nature",
        "short_description": "Hands-on science with live rescue reptiles, wild park hikes, and habitat exploration.",
        "description": "Meet real rescue lizards, snakes, frogs, and tortoises! Tree Frog Treks combines interactive animal care, hands-on science experiments, and outdoor nature hikes across Mission Dolores Park and Golden Gate Park.",
        "cost": "$295 / week",
        "cost_value": 295,
        "age_range": "5 - 11 yrs",
        "pills": ["Live Animals", "Nature Hikes", "SF Classic"],
        "img_idx": 2,
        "address": "Mission Dolores Park Hub, San Francisco, CA (1.9 mi away)",
        "dist": 1.9,
        "website": "https://www.treefrogtreks.com"
    },
    {
        "city": "San Francisco",
        "region": "SF",
        "zip_codes": ["94103", "94118", "94129"],
        "name": "Wheel Kids Bicycle Club Adventure Camp",
        "organizer": "Wheel Kids Bicycle Club",
        "category": "Sports",
        "short_description": "Cycling skill building, trail exploration, bike mechanics, and road safety for kids.",
        "description": "Build confidence on two wheels! Wheel Kids offers learn-to-ride coaching for beginners and urban trail adventure rides across SF parkways for intermediate riders. Focuses on road safety, gear shifting, and mechanical basics.",
        "cost": "$280 / week",
        "cost_value": 280,
        "age_range": "5 - 12 yrs",
        "pills": ["Biking", "Outdoors", "Active Play"],
        "img_idx": 3,
        "address": "Presidio & Golden Gate Park Hubs, SF (3.5 mi away)",
        "dist": 3.5,
        "website": "https://wheelkids.com"
    },
    {
        "city": "San Francisco",
        "region": "SF",
        "zip_codes": ["94103", "94122", "94116"],
        "name": "Camp EDMO STEAM & Social-Emotional Learning",
        "organizer": "Camp EDMO",
        "category": "STEM",
        "short_description": "Maker projects, coding, chemistry, and growth mindset design challenges.",
        "description": "A high-impact non-profit STEAM program! Kids engage in hands-on science experiments, maker engineering, and digital design while developing social-emotional intelligence, curiosity, and creative resilience.",
        "cost": "$330 / week",
        "cost_value": 330,
        "age_range": "5 - 13 yrs",
        "pills": ["STEAM", "Maker Lab", "Growth Mindset"],
        "img_idx": 0,
        "address": "Sunset District & Forest Hill, SF (4.2 mi away)",
        "dist": 4.2,
        "website": "https://campedmo.org"
    },
    {
        "city": "San Francisco",
        "region": "SF",
        "zip_codes": ["94103", "94115", "94109"],
        "name": "JCCSF After-School Enrichment & Youth Center",
        "organizer": "Jewish Community Center of San Francisco",
        "category": "After-School",
        "short_description": "Licensed after-school care with swimming, LEGO mechanics, arts, and homework support.",
        "description": "The premier comprehensive youth enrichment center in San Francisco! Features aquatics swimming lessons, youth sports leagues, pottery, dance, and quiet homework supervision with school pickup services.",
        "cost": "$210 / month",
        "cost_value": 210,
        "age_range": "5 - 12 yrs",
        "pills": ["After-School", "Aquatics", "Homework Support"],
        "img_idx": 1,
        "address": "3200 California St, Pacific Heights, SF (3.8 mi away)",
        "dist": 3.8,
        "website": "https://www.jccsf.org"
    }
]

# Grounded Real Seattle Programs (98101 / Seattle Region)
seattle_programs = [
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98109", "98103", "98104", "98122", "98115"],
        "name": "Pacific Science Center Camps for Curious Minds",
        "organizer": "Pacific Science Center",
        "category": "STEM",
        "short_description": "Robotics, space astronomy, coding, biology, and hands-on chemistry labs at Seattle Center.",
        "description": "Located at iconic Seattle Center! Kids dive into hands-on robotics, space discovery, coding, veterinary science, biology, and engineering. Programs are heavily inquiry-based and taught by expert science educators.",
        "cost": "$360 / week",
        "cost_value": 360,
        "age_range": "4 - 14 yrs",
        "pills": ["Seattle Center", "Robotics", "Top Ranked"],
        "img_idx": 0,
        "address": "200 2nd Ave N, Seattle Center, Seattle, WA 98109 (1.1 mi away)",
        "dist": 1.1,
        "website": "https://www.pacificsciencecenter.org"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98103", "98117", "98107"],
        "name": "Woodland Park Zoo Wildlife Rangers Camp",
        "organizer": "Woodland Park Zoo",
        "category": "Nature",
        "short_description": "Animal tracking, zookeeper meet-and-greets, wildlife conservation, and outdoor science.",
        "description": "Campers utilize the world-renowned Woodland Park Zoo grounds as their living classroom! Activities include tracking animal behavior, meeting zookeepers, building empathy for nature, and learning about global wildlife conservation.",
        "cost": "$310 / week",
        "cost_value": 310,
        "age_range": "4 - 13 yrs",
        "pills": ["Zoo Rangers", "Animal Science", "Outdoors"],
        "img_idx": 2,
        "address": "5500 Phinney Ave N, Phinney Ridge, Seattle, WA 98103 (4.2 mi away)",
        "dist": 4.2,
        "website": "https://www.zoo.org"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98109", "98121", "98102"],
        "name": "Seattle Children's Theatre Drama School Camp",
        "organizer": "Seattle Children's Theatre (SCT)",
        "category": "Arts",
        "short_description": "Creative drama storytelling, musical theater rehearsals, stage combat, and live youth shows.",
        "description": "Led by professional Seattle teaching artists! Camps range from creative play and storytelling for younger kids to full-scale musical theater creation, acting techniques, stage combat, and technical theater.",
        "cost": "$290 / week",
        "cost_value": 290,
        "age_range": "5 - 16 yrs",
        "pills": ["Theater", "Musical Comedy", "Seattle Center"],
        "img_idx": 1,
        "address": "201 Thomas St, Seattle Center, Seattle, WA 98109 (1.2 mi away)",
        "dist": 1.2,
        "website": "https://www.sct.org"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98103", "98115", "98122"],
        "name": "Girls Rock Math Creative Arts & Math Enrichment",
        "organizer": "Girls Rock Math",
        "category": "Academic",
        "short_description": "Arts-based math discovery, architecture design, secret codes, and spatial logic games.",
        "description": "Empowering, arts-based math enrichment designed to boost confidence! Instead of traditional classroom drilling, campers explore math through architecture, fashion design, crafting, secret codes, and nature patterns.",
        "cost": "$280 / week",
        "cost_value": 280,
        "age_range": "6 - 12 yrs",
        "pills": ["Girls Rock Math", "Creative Math", "Logic Games"],
        "img_idx": 0,
        "address": "Capitol Hill & Green Lake Sites, Seattle, WA (2.4 mi away)",
        "dist": 2.4,
        "website": "https://www.girlsrockmath.org"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98115", "98105"],
        "name": "Arena Sports Magnuson Youth Soccer & FunZone Camp",
        "organizer": "Arena Sports",
        "category": "Sports",
        "short_description": "Indoor soccer technical drills, teamwork agility games, and inflatable FunZone obstacle play.",
        "description": "High-energy indoor sports training and multi-activity play! Combines technical soccer skill development, teamwork agility, and access to giant indoor inflatables and obstacle courses.",
        "cost": "$260 / week",
        "cost_value": 260,
        "age_range": "3 - 12 yrs",
        "pills": ["Soccer Skills", "FunZone Inflatables", "High Energy"],
        "img_idx": 3,
        "address": "7751 63rd Ave NE, Magnuson Park, Seattle, WA 98115 (6.8 mi away)",
        "dist": 6.8,
        "website": "https://www.arenasports.net"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98104", "98121"],
        "name": "Seattle Aquarium Marine Science Explorers",
        "organizer": "Seattle Aquarium",
        "category": "Nature",
        "short_description": "Ocean conservation, harbor seal observations, tide pool sea stars, and Puget Sound ecology.",
        "description": "Located directly on Pier 59 along the waterfront! Children explore Puget Sound marine life, observe sea otters and harbor seals, sample microscopic plankton, and participate in shoreline conservation projects.",
        "cost": "$325 / week",
        "cost_value": 325,
        "age_range": "5 - 12 yrs",
        "pills": ["Waterfront", "Sea Otters", "Marine Bio"],
        "img_idx": 2,
        "address": "1483 Alaskan Way, Pier 59 Waterfront, Seattle, WA 98101 (0.6 mi away)",
        "dist": 0.6,
        "website": "https://www.seattleaquarium.org"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98104", "98121"],
        "name": "Parkour Visions Downtown Youth Movement & Obstacles",
        "organizer": "Parkour Visions",
        "category": "Sports",
        "short_description": "Obstacle navigation, spatial balance, safe parkour movement, and active play in 98101.",
        "description": "Located right in downtown 98101! Parkour Visions helps children build physical literacy, spatial awareness, and self-confidence through safe obstacle navigation, balance beams, and climbing walls.",
        "cost": "$270 / week",
        "cost_value": 270,
        "age_range": "5 - 14 yrs",
        "pills": ["Downtown 98101", "Parkour", "Active Movement"],
        "img_idx": 3,
        "address": "700 Seneca St, Downtown Seattle, WA 98101 (0.2 mi away)",
        "dist": 0.2,
        "website": "https://www.parkourvisions.org"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98104", "98109"],
        "name": "Seattle Architecture Foundation Youth Design & City Builders",
        "organizer": "Seattle Architecture Foundation",
        "category": "STEM",
        "short_description": "3D model building, urban city planning, bridge engineering, and eco-architecture in 98101.",
        "description": "Headquartered centrally in downtown 98101! Youth explore structural engineering, 3D model crafting, and sustainable urban design using Seattle's iconic skyline as a real-world classroom.",
        "cost": "$315 / week",
        "cost_value": 315,
        "age_range": "7 - 15 yrs",
        "pills": ["Downtown 98101", "Architecture", "3D Models"],
        "img_idx": 0,
        "address": "1700 7th Ave, Downtown Seattle, WA 98101 (0.3 mi away)",
        "dist": 0.3,
        "website": "https://www.seattlearchitecture.org"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98104"],
        "name": "Spruce Street School Downtown Outdoor Explorer Camp",
        "organizer": "Spruce Street School",
        "category": "Nature",
        "short_description": "Field trips to Puget Sound beaches, city park hikes, arts and crafts, and outdoor play.",
        "description": "A downtown Seattle favorite! Spruce Street School leads daily outdoor field trips to local beaches, parks, museums, and zoos, balanced with creative art workshops.",
        "cost": "$285 / week",
        "cost_value": 285,
        "age_range": "5 - 10 yrs",
        "pills": ["Downtown Core", "Beach Trips", "Outdoor Hikes"],
        "img_idx": 2,
        "address": "914 Virginia St, Central Seattle, WA 98101 (0.4 mi away)",
        "dist": 0.4,
        "website": "https://www.sprucestreetschool.org"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98109", "98103"],
        "name": "Kong Academy Parkour & Social-Emotional Growth",
        "organizer": "Kong Academy",
        "category": "Sports",
        "short_description": "Playful parkour obstacle courses, social-emotional growth, and outdoor movement.",
        "description": "Dynamic active movement! Kong Academy combines fun parkour obstacle courses with social-emotional growth lessons, teaching kids resilience, courage, and teamwork.",
        "cost": "$265 / week",
        "cost_value": 265,
        "age_range": "4 - 12 yrs",
        "pills": ["Parkour", "Growth Mindset", "Outdoor Play"],
        "img_idx": 3,
        "address": "Queen Anne & Gas Works Park, Seattle, WA (2.1 mi away)",
        "dist": 2.1,
        "website": "https://www.kongacademy.org"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98104"],
        "name": "YMCA of Greater Seattle Youth Center & Aquatics",
        "organizer": "YMCA of Greater Seattle",
        "category": "After-School",
        "short_description": "Licensed after-school care, swimming lessons, youth basketball, and outdoor adventure.",
        "description": "Located in downtown Seattle! Offers comprehensive licensed after-school enrichment, aquatics swimming lessons, youth basketball leagues, and weekend outdoor adventure camps.",
        "cost": "$195 / month",
        "cost_value": 195,
        "age_range": "5 - 13 yrs",
        "pills": ["After-School", "Downtown Y", "Swimming"],
        "img_idx": 1,
        "address": "909 4th Ave, Downtown Seattle, WA 98104 (0.5 mi away)",
        "dist": 0.5,
        "website": "https://www.seattleymca.org"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98108", "98118"],
        "name": "The Museum of Flight Aerospace & Rocketry Camp",
        "organizer": "The Museum of Flight",
        "category": "STEM",
        "short_description": "Model rocket building, flight simulator training, aviation history, and astronautics.",
        "description": "Reach for the skies at the world's premier air and space museum! Campers build model rockets, fly full-motion flight simulators, and explore historical aircraft cockpits.",
        "cost": "$345 / week",
        "cost_value": 345,
        "age_range": "7 - 15 yrs",
        "pills": ["Rockets", "Flight Sim", "Aviation"],
        "img_idx": 0,
        "address": "9404 E Marginal Way S, Seattle, WA 98108 (7.1 mi away)",
        "dist": 7.1,
        "website": "https://www.museumofflight.org"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98103", "98115"],
        "name": "Pedalheads Bicycle & Traffic Safety Camp",
        "organizer": "Pedalheads",
        "category": "Sports",
        "short_description": "Specialized bicycle instruction taking kids from training wheels to road riding confidence.",
        "description": "Renowned summer bike coaching! Pedalheads takes kids from training wheels to road and trail confidence in small, encouraging group sessions.",
        "cost": "$275 / week",
        "cost_value": 275,
        "age_range": "3 - 12 yrs",
        "pills": ["Biking", "Road Safety", "Confidence"],
        "img_idx": 3,
        "address": "Green Lake & Ravenna Park Hubs, Seattle, WA (4.5 mi away)",
        "dist": 4.5,
        "website": "https://pedalheads.com"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98144", "98122"],
        "name": "Seattle Bouldering Project Youth Climbing Camp",
        "organizer": "Seattle Bouldering Project",
        "category": "Sports",
        "short_description": "Indoor bouldering, climbing safety, balance agility games, and problem solving.",
        "description": "High-energy indoor climbing! Youth learn bouldering techniques, harness safety, spatial balance, and route-solving in a vibrant climbing gym setting.",
        "cost": "$295 / week",
        "cost_value": 295,
        "age_range": "6 - 14 yrs",
        "pills": ["Bouldering", "Rock Climbing", "Central District"],
        "img_idx": 3,
        "address": "900 Poplar Pl S, Central District, Seattle, WA 98144 (1.8 mi away)",
        "dist": 1.8,
        "website": "https://seattleboulderingproject.com"
    },
    {
        "city": "Seattle",
        "region": "Seattle",
        "zip_codes": ["98101", "98104"],
        "name": "Seattle Art Museum Young Artists Fine Arts Studio",
        "organizer": "Seattle Art Museum (SAM)",
        "category": "Arts",
        "short_description": "Fine art painting, sculpture, SAM gallery tours, and multimedia creative storytelling.",
        "description": "Located in downtown 98101! Young artists tour the museum's galleries for inspiration, then paint, sculpt, and create multimedia art in SAM's studio space.",
        "cost": "$300 / week",
        "cost_value": 300,
        "age_range": "6 - 13 yrs",
        "pills": ["SAM Museum", "Fine Arts", "Downtown 98101"],
        "img_idx": 1,
        "address": "1300 1st Ave, Downtown Seattle, WA 98101 (0.4 mi away)",
        "dist": 0.4,
        "website": "https://www.seattleartmuseum.org"
    }
]

# Combine both datasets
all_raw = sf_programs + seattle_programs
programs = []

for idx, item in enumerate(all_raw):
    # Registration date offset between +1 day and +90 days
    days_offset = 2 + (idx * 3) % 86
    reg_date = base_date + timedelta(days=days_offset)
    
    session_start = reg_date + timedelta(days=7 + (idx % 5))
    session_end = session_start + timedelta(days=5 if item["category"] != "After-School" else 30)
    
    program = {
        "id": f"camp-{idx+1:03d}",
        "city": item["city"],
        "region": item["region"],
        "zip_codes": item.get("zip_codes", []),
        "name": item["name"],
        "organizer": item["organizer"],
        "category": item["category"],
        "short_description": item["short_description"],
        "description": item["description"],
        "cost": item["cost"],
        "cost_value": item["cost_value"],
        "hero_image": images[item["img_idx"] % len(images)],
        "pills": item["pills"],
        "age_range": item["age_range"],
        "distance_miles": item["dist"],
        "location_address": item["address"],
        "registration_date": reg_date.strftime("%Y-%m-%d"),
        "registration_display": reg_date.strftime("%b %d, %Y"),
        "session_dates": f"{session_start.strftime('%b %d')} - {session_end.strftime('%b %d, %Y')}",
        "website_url": item["website"],
        "featured": idx % 6 == 0,
        "fit_rank": idx + 1
    }
    programs.append(program)

with open("/home/user/build-with-gemini/schoolhouse-camps/data/programs.json", "w") as f:
    json.dump(programs, f, indent=2)

print(f"Generated {len(programs)} multi-region grounded programs successfully.")
